### ISSUE TITLE
Getting a lot of errors

### ISSUE THREAD

**Issue by str1438** [run-youngjoo/SC-FEGAN#35]
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\imp.py", line 2
42, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\imp.py", line 3
42, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from model import Model
  File "C:\Users\Noah\Documents\SC-FEGAN-master\model.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\site-packages\t
ensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\imp.py", line 2
42, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\imp.py", line 3
42, in load_dynamic
    return _load(spec)

What's the problem here? All the dependencies are installed. I use Python 3.7.3

**Comment by Kogam22** [comment]
@str1438 Maybe try with python3.6 ?
